server:
  port: 9100
spring:
  application:
    name: ch2-springboot
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kotlin?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoReconnect=true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
       hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
